# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c884455091a09b34ae70455d692491e560c5cd4f1b210ba9ca793123c76875489f310f4a9dcc2ebc001d38f84e44dd7fc0903b7f8bed0d8d107a51e915facb5

test:
  secret_key_base: 7485b538f79532e9ea4382d4efaf2939f4ceb38e1d2eab293f7691a5ce7030b306092568f9dc7aa9e38cbc098c793026fc35f28240a79eaa88a9bf97616a4102

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
